version: 1.0.{build}
image:
- Visual Studio 2022
- Visual Studio 2019
- Visual Studio 2017
environment:
  _CRT_SECURE_NO_WARNINGS: 1
  _SCL_SECURE_NO_WARNINGS: 1
install:
- sh: python -m pip install meson ninja
build_script:
- sh: >-
    meson setup build -Dwith_test=enabled

    meson compile -C build
test_script:
- sh: meson test -C build -v --test-args='--mode devops'
